# -- Theme Options --
# Blowfish Theme Configuration
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true

enableA11y = false
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

mainSections = ["posts"]

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false

Logo = "img/head.jpg"

# Use existing background image
defaultBackgroundImage = "img/top_img.jpg"
defaultFeaturedImage = "img/top_img.jpg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

fingerprintAlgorithm = "sha512"

customCSS = ["css/custom.css"]

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "img/top_img.jpg"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = false
  cardViewScreenWidth = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "background"
  showComments = true
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showCategoryOnly = false
  showAuthorsBadges = false
  showWordCount = true
  showZenMode = false
  codeBlockFoldThreshold = 18
  codeBlockFoldExpandByDefault = false

[list]
  showHero = false
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = false
  orderByWeight = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

[term]
  showHero = false
  showBreadcrumbs = true
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
